// AUTO-GENERATED from /Users/rcyeager/appdev_root/apiant-website/ai-operability.html
// by scripts/extract-fred-when.ts. Do not hand-edit; re-run the script.
// Source of truth is Fred's page data-* attrs on every .card and on the
// hidden <template id="tool-details-data"> block.

export type CardMetadata = {
  title?: string;
  desc?: string;
  when?: string;
  category?: string;
  mutation?: "read" | "write";
  kind?: "skill" | "tool";
  invokes?: string[];
  usedBy?: string[];
};

export const CARD_METADATA: Record<string, CardMetadata> = {
  ["/alert-handling"]: {
    title: "Tune alert behavior",
    desc: "Control which errors retry, which 401s bypass auto-turnoff, alert text rewriting, dismissal lists.",
    when: "When noisy alerts or auto-turnoffs are getting in the way. Adjust retry policy, carve out 401 domains that should not auto-disable, rewrite alert copy for customer-facing reports, suppress known-good errors.",
    category: "ops",
    kind: "skill",
    invokes: ["alert_suppress","alert_unsuppress","alert_list_suppressed","alert_get_error_policy","alert_get_automation_mappings","alert_set_automation_mappings","admin_ignore_401_domains","admin_retryable_errors"],
  },
  ["/apiant-setup"]: {
    title: "Set up the plugin",
    desc: "Verify MCP connections, environment, and plugin version. Run on first install or when something breaks.",
    when: "When installing the plugin for the first time, after upgrades, or when a skill fails to load. Running this first eliminates environment issues before you debug real work.",
    category: "setup",
    kind: "skill",
    invokes: ["deploy_get_plugin_version","activate_toolset"],
  },
  ["/build-assembly"]: {
    title: "Build an app assembly",
    desc: "The integration plumbing: OAuth, API Key, or no-cred connectors, triggers, and actions (ADD/GET/LIST/UPDATE/DELETE/FIND).",
    when: "When there is no catalog app yet for the system you want to integrate, or an existing assembly is missing an operation. This builds the low-level connector + operations that /build-automation later composes into a flow.",
    category: "build",
    kind: "skill",
    invokes: ["asm_create_connector","asm_create_action_or_trigger","asm_create_action_input_fields","asm_set_output_fields","asm_set_jsp_and_compile","asm_test_api_endpoint","asm_inject_settings"],
  },
  ["/build-automation"]: {
    title: "Build a new automation",
    desc: "\"Connect X to Y.\" Claude picks triggers, actions, field mappings, and stands up the entire flow.",
    when: "When the user says \"connect X to Y\" or \"build a flow that does Z.\" This is the primary entry point for any new integration. Claude picks a trigger skill, action skills, and patterns as needed.",
    category: "build",
    kind: "skill",
    invokes: ["auto_build","auto_manage","auto_commit","auto_edit_mapping","auto_edit_structure","catalog_search_apps","pattern_search"],
  },
  ["/build-form"]: {
    title: "Design a form",
    desc: "Form schema for lead capture, onboarding, or config, wired straight into an APIANT automation.",
    when: "When the automation needs human input. Lead capture, customer onboarding, config collection, approval prompts. Claude designs the schema and wires it into an existing automation.",
    category: "build",
    kind: "skill",
    invokes: ["auto_get_form_design","auto_save_form_design","auto_get_form_element_catalog","auto_get_form_patterns","auto_refresh_form_fields","auto_validate_forms"],
  },
  ["/build-integration"]: {
    title: "Build an integration suite",
    desc: "Multi-automation deployments: two-way sync, data pipelines, coordinated workflows with shared state.",
    when: "When a customer needs more than one automation working together, for example a two-way contact sync plus an invoice pipeline plus a daily reconciliation. Scopes the work, then delegates to /build-automation for each piece.",
    category: "build",
    kind: "skill",
    invokes: ["auto_build","auto_manage","auto_folder","pattern_search","pattern_save"],
  },
  ["/convert-assembly"]: {
    title: "Convert human to AI template",
    desc: "Migrate legacy human-built assemblies to the AI-template pattern so Claude can safely edit them.",
    when: "When a legacy assembly (hand-authored, not AI-template-shaped) needs to be edited by Claude. Converts the structure to the AI-template conventions so /edit-assembly becomes safe.",
    category: "connector",
    kind: "skill",
    invokes: ["asm_read_assembly_logic","asm_set_jsp_and_compile","asm_cleanup","asm_find_referencers"],
  },
  ["/deploy-automation"]: {
    title: "Deploy dev to prod",
    desc: "Publish template automations and push linked deployments to customer accounts in one coordinated step.",
    when: "Once tests pass. Promotes a draft to the dev template, then optionally pushes the template to linked customer accounts in prod. A single coordinated step; if any account fails, the deploy reports clearly.",
    category: "test",
    kind: "skill",
    invokes: ["deploy_publish_assembly","deploy_publish_folder","deploy_to_accounts","deploy_list_linked_accounts","auto_set_active"],
  },
  ["/edit-assembly"]: {
    title: "Edit an assembly",
    desc: "Fix JSP, update API calls, change endpoints, rename settings, edit dropdowns, with full diff awareness.",
    when: "When an API changes (new endpoint, renamed field, deprecated operation) and the assembly needs to catch up. Read the current logic, apply the diff, recompile, and validate.",
    category: "edit",
    kind: "skill",
    invokes: ["asm_read_assembly_logic","asm_set_jsp_and_compile","asm_inject_settings","asm_reset_settings","asm_set_output_fields","asm_cleanup","asm_find_referencers"],
  },
  ["/edit-automation"]: {
    title: "Edit an automation",
    desc: "Add a step, fix the mapping, swap Mailchimp for Klaviyo, disable a branch. Surgical, non-destructive edits.",
    when: "When you need to modify an existing, committed automation: add a step, change a mapping, swap connectors, retitle, disable a branch. Changes land as a new draft version, never in place.",
    category: "edit",
    kind: "skill",
    invokes: ["auto_edit_structure","auto_edit_mapping","auto_edit_metadata","auto_edit_trigger","auto_apply_edits","auto_commit","auto_get_step_details"],
  },
  ["/monitor-account"]: {
    title: "Monitor a customer account",
    desc: "Watches prod automations for errors. Designed for /loop recurring runs. Alerts with full trace context.",
    when: "Continuous background check on a prod tenant. Runs on /loop, inspects failures since last check, raises alerts with full stack + last good input. Designed for always-on SRE duty.",
    category: "ops",
    kind: "skill",
    invokes: ["admin_switch_account","admin_tenant_health","admin_tenant_usage","exec_search_history","exec_get_history","admin_account_changelog"],
  },
  ["/register-oauth-app"]: {
    title: "Register an OAuth app",
    desc: "Drive a dev browser to register an OAuth app on a vendor portal, capture client_id and secret into the keyvault.",
    when: "First time integrating a new OAuth vendor. Claude drives a headless browser through the vendor developer portal, creates the app, copies client_id and secret into the keyvault, and annotates the redirect URLs.",
    category: "connector",
    kind: "skill",
    invokes: ["admin_save_keyvault_entry","admin_list_keyvault_entries"],
  },
  ["/support"]: {
    title: "Diagnose a customer issue",
    desc: "\"Why did this not process?\" Claude searches execution history, traces failures, extracts HTTP, proposes a fix.",
    when: "Customer reports something went wrong. Claude pulls execution history, isolates the failing run, extracts the exact HTTP request/response, names the root cause, proposes a remediation.",
    category: "ops",
    kind: "skill",
    invokes: ["admin_switch_account","exec_search_history","exec_get_history","exec_get_assembly_log","exec_get_step_data","exec_retry_failed","auto_get_summary"],
  },
  ["/test-automation"]: {
    title: "Test an automation",
    desc: "Execute, inspect results, diagnose failures, apply fixes, retest, and run branch coverage automatically.",
    when: "After any edit, or when a customer reports something wrong. Runs the automation end-to-end with realistic inputs, walks every branch, and surfaces the failing step with the exact HTTP request and response.",
    category: "test",
    kind: "skill",
    invokes: ["exec_test_automation","exec_get_data","exec_get_step_data","exec_get_branch_test_points","exec_mutate_data","exec_restart_from_step","exec_retry_failed"],
  },
  ["/test-integration"]: {
    title: "Test the whole suite",
    desc: "Validate data flow between automations, shared state, loop prevention, and cross-automation coordination.",
    when: "For multi-automation suites where the automations interact. Especially critical for two-way syncs: Claude stages data, watches for echo loops, and verifies conflict resolution.",
    category: "test",
    kind: "skill",
    invokes: ["exec_test_automation","exec_test_subroutine","exec_get_assembly_log","exec_search_history"],
  },
  ["activate_toolset"]: {
    title: "Activate a toolset",
    desc: "Load the specific toolset needed for the current skill. Keeps the context window lean.",
    when: "Called at the start of a skill to pull in the specialized tools for the job. Without this, the full 125 would crowd the context every turn.",
    category: "tools",
    mutation: "read",
    kind: "tool",
  },
  ["admin"]: {
    title: "Tenant ops",
    desc: "25 tools. Switch between customer accounts, query usage and health across a tenant, read the keyvault, run ad-hoc SQL, tune retryable errors, manage lookups. The operator's toolbox.",
    when: "Activated by /support, /monitor-account, /alert-handling. Contains admin_switch_account, admin_list_tenants, admin_sql_query, admin_tenant_health, keyvault helpers.",
    category: "tools",
    mutation: "write",
    kind: "tool",
  },
  ["admin_alerts"]: {
    title: "Alert governance",
    desc: "5 tools. Tenant-wide alert rules, suppressed-alert lists, retry policy, 401 domain carve-outs. Requires Switch Account context.",
    when: "Activated by /alert-handling. A narrower surface than admin, scoped specifically to alert policy: suppression lists, retryable errors, 401 domain ignore, alert mappings.",
    category: "tools",
    mutation: "write",
    kind: "tool",
  },
  ["admin_sql_query"]: {
    title: "Read-only SQL query",
    when: "When diagnosing customer issues or validating data-level hypotheses.",
    category: "admin",
    mutation: "read",
    usedBy: ["/support","/monitor-account"],
  },
  ["alert_set_system_mappings"]: {
    title: "Set tenant alert rules",
    when: "When tuning alert behavior after a noisy incident.",
    category: "alerts",
    mutation: "write",
    usedBy: ["/alert-handling"],
  },
  ["alerts"]: {
    title: "Alert mapping",
    desc: "11 tools. Per-automation alert mapping rules, step-level alert triggers, mapping trace, suppression, system-level mappings.",
    when: "Activated by /alert-handling when the fix is at the automation or step level rather than tenant-wide. Contains alert_get/set_automation_mappings, alert_get_mapping_trace, alert_suppress.",
    category: "tools",
    mutation: "write",
    kind: "tool",
  },
  ["asm_create_connector"]: {
    title: "Create an app connector",
    when: "When building an integration for an app APIANT does not yet support.",
    category: "assembly",
    mutation: "write",
    usedBy: ["/build-assembly","/register-oauth-app"],
  },
  ["asm_execute"]: {
    title: "Execute an assembly action",
    when: "After asm_set_jsp_and_compile succeeds, to verify the assembly works against the real API.",
    category: "assembly",
    mutation: "write",
    usedBy: ["/build-assembly","/edit-assembly","/test-automation"],
  },
  ["asm_manage"]: {
    title: "Manage assemblies",
    desc: "Load, list, create, update, rename, and delete assemblies. The low-level assembly API.",
    when: "The universal entry for assembly operations: list to browse, load to read, create/update/delete to modify. Most assembly work flows through this single dispatcher.",
    category: "tools",
    mutation: "write",
    kind: "tool",
  },
  ["asm_set_jsp_and_compile"]: {
    title: "Write and compile JSP",
    when: "Core assembly authoring step, called after an action or trigger skeleton is created.",
    category: "assembly",
    mutation: "write",
    usedBy: ["/build-assembly","/edit-assembly","assembly-action-add","assembly-action-update","assembly-action-find","assembly-action-get","assembly-action-list","assembly-action-delete"],
  },
  ["assembly"]: {
    title: "Connector + assembly build",
    desc: "28 tools. Create connectors, inject settings, compile JSP, test API endpoints, wire dynamic field discovery, finalize assemblies. The low-level integration plumbing.",
    when: "Activated by /build-assembly and /edit-assembly. Contains asm_create_connector, asm_create_action_or_trigger, asm_set_jsp_and_compile, asm_test_api_endpoint, asm_inject_settings, and more.",
    category: "tools",
    mutation: "write",
    kind: "tool",
  },
  ["assembly-action-add"]: {
    title: "ADD",
    desc: "Create a new record in the target app. Handles validation, required fields, and response parsing.",
    when: "When you need to write a new record downstream: a new client, a new order, a new ticket. ADD owns validation, required-field checks, and parsing the response id back for later steps.",
    category: "actions",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger","asm_create_action_input_fields","asm_set_output_fields"],
  },
  ["assembly-action-delete"]: {
    title: "DELETE",
    desc: "Remove a record by ID or criteria. Safe-mode defaults with rollback metadata preserved.",
    when: "Rare by design. When a cleanup or GDPR workflow needs hard deletes. Defaults to safe mode: preserves a deletion log so the op is reversible where the API supports it.",
    category: "actions",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger","asm_create_action_input_fields"],
  },
  ["assembly-action-find"]: {
    title: "FIND",
    desc: "Search by criteria, return matches. Used for dedup, upsert, and enrichment patterns.",
    when: "Before an ADD, to upsert instead of duplicating. During enrichment, to look up a matching record. The \"does this already exist\" primitive.",
    category: "actions",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger","asm_create_action_input_fields","asm_set_output_fields"],
  },
  ["assembly-action-get"]: {
    title: "GET",
    desc: "Retrieve one record by ID. The simplest read path. Often chained after FIND or NEW.",
    when: "Simplest read. Usually downstream of a FIND (to hydrate the match) or of a NEW_ITEM trigger (to fetch full details when the trigger payload is lean).",
    category: "actions",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger","asm_set_output_fields"],
  },
  ["assembly-action-list"]: {
    title: "LIST",
    desc: "Page through results with cursor or offset handling. Rate-limit aware by default.",
    when: "Bulk reads: initial backfills, reconciliation jobs, reporting. Handles pagination, rate-limit headers, retry on 429. Avoid in per-record triggers; prefer FIND.",
    category: "actions",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger","asm_set_output_fields","asm_set_action_throttle"],
  },
  ["assembly-action-update"]: {
    title: "UPDATE",
    desc: "Patch existing records. Partial updates supported. Only touches the fields you specify.",
    when: "Two-way syncs, edits, status changes. Uses PATCH where available, partial POST otherwise. Only writes the fields you pass, never the whole record.",
    category: "actions",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger","asm_create_action_input_fields"],
  },
  ["assembly-bidirectional-sync"]: {
    title: "Bidirectional sync",
    desc: "Builds the matching trigger and action pair for a two-way sync. Handles loop prevention, last-write-wins, and conflict resolution out of the box.",
    when: "Whenever the customer says both systems should stay in lockstep: CRM <-> booking, ERP <-> accounting, shop <-> ops. The skill creates both directions with correlated IDs, loop suppression, and conflict rules baked in.",
    category: "sync",
    kind: "skill",
    invokes: ["auto_build","auto_commit","pattern_search"],
  },
  ["assembly-connector"]: {
    title: "Connector assembly",
    desc: "OAuth V2, API Key, or no-credential auth. Handles token refresh, scopes, and revocation.",
    when: "Every assembly starts with a connector. Pick OAuth V2 for user-delegated access, API Key for server-to-server, no-cred for open APIs. Token refresh and revocation are built in.",
    category: "connector",
    kind: "skill",
    invokes: ["asm_create_connector","asm_inject_settings","asm_get_connection_credentials","asm_set_connector_throttle"],
  },
  ["assembly-trigger-manual-webhook"]: {
    title: "Manual webhook",
    desc: "You paste a URL into the source app. Incoming posts fire the automation.",
    when: "When the source app has its own webhook UI and the customer is willing to paste a URL. Lowest lift, zero credential handling, works everywhere.",
    category: "triggers",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger","asm_set_webhook_field_xml","asm_add_webhook_support"],
  },
  ["assembly-trigger-new"]: {
    title: "NEW_ITEM polling trigger",
    desc: "Poll an endpoint on a schedule and fire when a new record appears. The workhorse trigger.",
    when: "When the source app does not offer webhooks, or its webhooks are unreliable. The workhorse trigger: poll every N minutes, compare a cursor field, fire on new records.",
    category: "triggers",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger","asm_set_output_fields","asm_test_api_endpoint"],
  },
  ["assembly-trigger-protocol-thread"]: {
    title: "Protocol thread",
    desc: "APIANT-to-APIANT internal protocol. Enables chained automations across accounts and environments.",
    when: "When one automation needs to hand off to another, possibly in a different tenant, without going back out to HTTP. Lower latency, typed payloads, survives network flakes.",
    category: "triggers",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger"],
  },
  ["assembly-trigger-self-registering-webhook"]: {
    title: "Self-registering webhook",
    desc: "APIANT creates and tears down the webhook automatically via the target app's API. Zero manual setup.",
    when: "When the target app exposes a webhook registration API. APIANT subscribes on activation, unsubscribes on teardown, zero manual work on the customer side.",
    category: "triggers",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger","asm_add_webhook_support","asm_set_webhook_field_xml"],
  },
  ["assembly-trigger-service-webhook"]: {
    title: "Service webhook",
    desc: "Credential-based webhook URL with event filtering. Multiple event types route on a single endpoint.",
    when: "When one endpoint needs to accept many event types and route them. The credential drives the URL, and an event discriminator picks the branch.",
    category: "triggers",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger","asm_set_webhook_field_xml","asm_add_webhook_support"],
  },
  ["assembly-trigger-updated"]: {
    title: "NEW_OR_UPDATED polling",
    desc: "Polls and fires when a record is created or modified. Tracks last-seen cursor automatically.",
    when: "When you care about edits, not just inserts. Same polling shape as NEW_ITEM but the cursor watches a last_modified timestamp so changes also fire.",
    category: "triggers",
    kind: "skill",
    invokes: ["asm_create_action_or_trigger","asm_set_output_fields"],
  },
  ["auto_build"]: {
    title: "Build an automation draft",
    when: "When Claude is building a new automation from a natural-language prompt.",
    category: "automation_builder",
    mutation: "write",
    usedBy: ["/build-automation","/build-integration","/edit-automation"],
  },
  ["auto_commit"]: {
    title: "Commit a draft to the dashboard",
    when: "After auto_build generates a draft and tests pass against it.",
    category: "automation_builder",
    mutation: "write",
    usedBy: ["/build-automation","/build-integration"],
  },
  ["auto_edit_structure"]: {
    title: "Edit automation steps",
    when: "When the user says \"add a step\" or \"swap this app for that one\".",
    category: "automation_builder",
    mutation: "write",
    usedBy: ["/edit-automation"],
  },
  ["auto_folder"]: {
    title: "List folders",
    desc: "Navigate the folder tree. Find automations grouped by customer, product, or environment.",
    when: "When organizing or finding automations grouped by customer, vertical, or product. Pair with auto_list for a two-step browse.",
    category: "tools",
    mutation: "read",
    kind: "tool",
  },
  ["auto_get_summary"]: {
    title: "Automation summary",
    desc: "Structured overview of an automation: triggers, steps, mappings. Fast context for edits.",
    when: "First call before editing an existing automation. Gives Claude the shape (triggers, step tree, mappings) without pulling the full source, so subsequent edit calls land accurately.",
    category: "tools",
    mutation: "read",
    kind: "tool",
  },
  ["auto_list"]: {
    title: "List automations",
    desc: "Flat list of every automation in a scope. Filter by name, folder, or status.",
    when: "When you need to find something by name or status (\"all HubSpot automations that failed in the last hour\"). Returns a flat list, does not fetch bodies.",
    category: "tools",
    mutation: "read",
    kind: "tool",
  },
  ["auto_manage"]: {
    title: "Manage automations",
    desc: "Create, rename, duplicate, move, enable, disable. Every CRUD operation for automations.",
    when: "The universal entry for automation CRUD. Create draft, rename, move across folders, enable/disable. Every skill that writes touches this.",
    category: "tools",
    mutation: "write",
    kind: "tool",
  },
  ["automation_builder"]: {
    title: "Build + edit",
    desc: "30 tools. Search the catalog, compose triggers and actions, edit mappings, commit versions, save patterns. The full automation authoring surface.",
    when: "Activated by /build-automation and /edit-automation. Contains auto_build, auto_edit_* family, catalog_search, pattern_search/save.",
    category: "tools",
    mutation: "write",
    kind: "tool",
  },
  ["automation_exec"]: {
    title: "Runtime inspection",
    desc: "17 tools. Run test executions, inspect every step's input and output, mutate data, replay webhooks, walk branch-coverage test points. Debugging with full ground truth.",
    when: "Activated by /test-automation and /support. Contains exec_test_automation, exec_get_* family, exec_retry_failed, exec_replay_webhook.",
    category: "tools",
    mutation: "write",
    kind: "tool",
  },
  ["automation_manage"]: {
    title: "Automation lifecycle",
    desc: "10 tools. List and organize committed automations, version them, compare versions, roll back. The git-like layer over automation drafts and releases.",
    when: "Activated by /build-integration, /edit-automation, /test-automation, /support. Contains auto_list, auto_manage, auto_commit, auto_list_versions, auto_compare_versions, auto_folder.",
    category: "tools",
    mutation: "write",
    kind: "tool",
  },
  ["catalog_list_apps"]: {
    title: "List catalog apps",
    desc: "The full catalog of available app integrations. Filter by category, vendor, or capability.",
    when: "Before /build-automation, to confirm both sides of the integration exist. \"Is there a Mindbody assembly? A Klaviyo one?\" Filter by vertical or capability.",
    category: "tools",
    mutation: "read",
    kind: "tool",
  },
  ["catalog_search_apps"]: {
    title: "Search the app catalog",
    when: "At the start of any build skill, to resolve natural-language app names to UUIDs.",
    category: "automation_builder",
    mutation: "read",
    usedBy: ["/build-automation","/build-assembly","/build-integration","/support"],
  },
  ["deploy"]: {
    title: "Dev to prod",
    desc: "6 tools. Publish folders or individual assemblies from dev to prod. Roll changes out to linked customer accounts in a single coordinated step.",
    when: "Activated by /deploy-automation. Contains deploy_publish_assembly, deploy_publish_folder, deploy_to_accounts, deploy_list_linked_accounts, deploy_update_plugin, deploy_get_plugin_version.",
    category: "tools",
    mutation: "write",
    kind: "tool",
  },
  ["deploy_publish_folder"]: {
    title: "Publish a folder to prod",
    when: "When promoting a folder of template automations to the production environment.",
    category: "deploy",
    mutation: "write",
    usedBy: ["/deploy-automation"],
  },
  ["docs_api_key"]: {
    title: "API key auth",
    desc: "Programmatic access. Issue a docs API key for CI/CD or automated publishing.",
    when: "When a CI pipeline or automation needs to publish docs without a human session. Issues a long-lived API key scoped to the docs workspace.",
    category: "tools",
    mutation: "write",
    kind: "tool",
    usedBy: ["/support","write-doc"],
  },
  ["docs_chat"]: {
    title: "Chat with docs",
    desc: "Retrieval-augmented Q&A. Claude asks the docs corpus before writing code or answering.",
    when: "When Claude needs authoritative answers grounded in APIANT docs before writing code or answering the user. Prefer this over memory for anything factual.",
    category: "tools",
    mutation: "read",
    kind: "tool",
    usedBy: ["/build-automation","/build-assembly","/support","write-doc"],
  },
  ["docs_create"]: {
    title: "Create a page",
    desc: "Publish a new doc. Title, body, parent, tags, and status, in one call.",
    when: "When the user asks Claude to document a feature, workflow, or gotcha. Also after shipping an assembly so the integration gets a customer-facing page.",
    category: "tools",
    mutation: "write",
    kind: "tool",
    usedBy: ["write-doc","/build-assembly"],
  },
  ["docs_list"]: {
    title: "List docs",
    desc: "Browse the full table of contents. Filter by section, tag, or status.",
    when: "When Claude needs to pick the right parent section before creating a doc, or to confirm nothing exists yet. The \"does this page already live somewhere\" primitive.",
    category: "tools",
    mutation: "read",
    kind: "tool",
    usedBy: ["write-doc","/build-automation"],
  },
  ["docs_login"]: {
    title: "Login",
    desc: "Authenticate the docs session. Tokens cached for the session.",
    when: "First call of any docs-writing skill. Establishes the session token; subsequent calls reuse the cached credential until it expires.",
    category: "tools",
    mutation: "write",
    kind: "tool",
    usedBy: ["write-doc","/support"],
  },
  ["docs_read"]: {
    title: "Read a page",
    desc: "Fetch the full contents of any doc. Markdown, images, and metadata included.",
    when: "When Claude needs the literal body of a page, not just a summary. Called before docs_update to diff intelligently or before answering a precise how-to question.",
    category: "tools",
    mutation: "read",
    kind: "tool",
    usedBy: ["write-doc","/support","/build-automation"],
  },
  ["docs_screenshot"]: {
    title: "Capture screenshot",
    desc: "Take a live screenshot of the editor or platform UI and embed it into a doc.",
    when: "When a how-to doc needs to show the actual editor UI. Claude drives a headless browser, captures the panel, and embeds the image inline.",
    category: "tools",
    mutation: "write",
    kind: "tool",
    usedBy: ["write-doc"],
  },
  ["docs_search"]: {
    title: "Full-text search",
    desc: "Semantic + keyword search across the entire docs corpus. Ranked results with context.",
    when: "When the user's question is open-ended and Claude needs to find the right page(s). Hybrid semantic + keyword ranking; returns snippets with source links.",
    category: "tools",
    mutation: "read",
    kind: "tool",
    usedBy: ["/support","/build-automation","write-doc"],
  },
  ["docs_update"]: {
    title: "Update a page",
    desc: "Edit title, body, tags, or status. Revisions tracked automatically.",
    when: "When a shipped change makes an existing doc stale: API deprecation, new field, renamed step. Always call docs_read first so the edit is a real diff.",
    category: "tools",
    mutation: "write",
    kind: "tool",
    usedBy: ["write-doc","/edit-assembly"],
  },
  ["docs_upload_image"]: {
    title: "Upload image",
    desc: "Attach an illustration or diagram to any page. Auto-alt-text generated.",
    when: "When a doc needs a diagram, architecture sketch, or external illustration that is not a UI screenshot. Auto-generates alt text from the caption.",
    category: "tools",
    mutation: "write",
    kind: "tool",
    usedBy: ["write-doc"],
  },
  ["docs_version"]: {
    title: "Version history",
    desc: "List revisions, diff between versions, roll back if needed.",
    when: "When a doc edit needs review, when a rollback is requested, or when Claude needs to reconstruct how guidance evolved over time.",
    category: "tools",
    mutation: "read",
    kind: "tool",
    usedBy: ["write-doc","/support"],
  },
  ["exec_replay_webhook"]: {
    title: "Replay a past webhook",
    when: "Customer support flow, when a specific event failed in production.",
    category: "automation_exec",
    mutation: "write",
    usedBy: ["/support","/test-automation"],
  },
  ["exec_test_automation"]: {
    title: "Test an automation",
    when: "When testing an automation before activation.",
    category: "automation_exec",
    mutation: "write",
    usedBy: ["/test-automation","/test-integration","/build-automation"],
  },
  ["pattern-chat-widget"]: {
    title: "Chat widget",
    desc: "From simple chatbots to multi-goal conversation flows with memory and tool-calling automations.",
    when: "When the trigger is a conversation: support chat, lead qualification, booking assistant. Pattern handles memory, tool calls into other automations, and fallback-to-human.",
    category: "patterns",
    kind: "skill",
    invokes: ["pattern_search","auto_build"],
  },
  ["pattern-csv-mapping"]: {
    title: "CSV field mapping",
    desc: "Drop in a spreadsheet of \"source field -> target field\" and Claude wires the mappings verbatim.",
    when: "Enterprise migrations. The customer hands over a spreadsheet of mappings. This pattern parses and wires them literally: no Claude improvisation, no surprise transforms.",
    category: "patterns",
    kind: "skill",
    invokes: ["auto_edit_mapping","pattern_search"],
  },
  ["pattern-execute-automation"]: {
    title: "Execute Automation chaining",
    desc: "Parent/child flows with query-string parameter passing and webhook payload forwarding.",
    when: "When the flow is too wide to live in one automation. Decompose into parent + children; parent triggers a child per record, passes parameters, then consolidates results.",
    category: "patterns",
    kind: "skill",
    invokes: ["pattern_search","auto_build"],
  },
  ["pattern-human-moderation"]: {
    title: "Human moderation",
    desc: "Pause an automation until a person approves or denies via moderation queue link. Decision gates for AI flows.",
    when: "Whenever an AI step writes to something consequential: sends outbound email, refunds money, deletes records. The pattern creates an approval URL, pauses, and resumes on decision.",
    category: "patterns",
    kind: "skill",
    invokes: ["pattern_search","auto_build"],
  },
  ["pattern-latches"]: {
    title: "Fan-out / fan-in latches",
    desc: "Launch N child automations in parallel, wait for all to finish, proceed with aggregated results.",
    when: "Bulk work that benefits from parallelism: enrich 500 contacts across a dozen APIs, then aggregate. Latch tracks N subruns, waits for all, rolls up the batch.",
    category: "patterns",
    kind: "skill",
    invokes: ["pattern_search","auto_build"],
  },
  ["pattern-snooze"]: {
    title: "Snooze",
    desc: "Pause an automation until a specific datetime. Useful for drip sequences and scheduled follow-ups.",
    when: "Time-based delays inside a run: drip sequences, scheduled follow-ups, cool-down periods. The step writes a wake-up and releases the run at the target time.",
    category: "patterns",
    kind: "skill",
    invokes: ["pattern_search","auto_build"],
  },
  ["pattern_search"]: {
    title: "Search the pattern library",
    when: "When Claude needs prior art before building. Loaded automatically by build skills.",
    category: "patterns",
    mutation: "read",
    usedBy: ["/build-automation","/build-assembly","/build-form","/build-integration","/support"],
  },
  ["patterns"]: {
    title: "Pattern library",
    desc: "3 tools. Search, save, and delete reusable pattern recipes: field mappings, transforms, gotchas, templates.",
    when: "Activated by /build-automation and the pattern-* skills. Contains pattern_search (find by shape), pattern_save (after a successful build), pattern_delete.",
    category: "tools",
    mutation: "write",
    kind: "tool",
  },
};
